### ISSUE TITLE
Error on intial commit to existing repo

### ISSUE THREAD

**Issue by jimbudarz** [microsoft/InclusivenessAnalyzer#31]
I'm not sure if this is because it's only scanning files added during the last commit (which only contains addition of this GitHub Action):
```
# This workflow checks out code and scans the content changed or added in the 
# last commit for offensive / exclusive terms.
# The scan will provide context on the found terms and alternatvies that can be
# used instead.

name: Inclusiveness Analyser scan

on:
  push:
  workflow_dispatch:

jobs:
  Inclusiveness-Analyser-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Inclusiveness Analyzer
      uses: microsoft/InclusivenessAnalyzer@v1.0.0
      with:
        # Fails the step if a non-inclusive term is found
        failOnNonInclusiveTerm: false
        # Only scan files added or modified in last commit when checkout step has "with: fetch-depth: 2" configured
        excludeUnchangedFiles: true
```

I'm getting the following error from the action:
```
Run microsoft/InclusivenessAnalyzer@v1.0.0
Notice: Inclusiveness Analyzer
Notice: - Scanning files added or modified in last commit
Error: ENOENT: no such file or directory, stat
```

**Comment by cblomart** [comment]
Hi @jimbudarz 

Can you rerun the job with debug logging enabled?
![image](https://user-images.githubusercontent.com/3999494/195782023-be85c061-8a13-44a6-95ee-8f8fd9e21fe2.png)

**Comment by jimbudarz** [comment]
> Hi @jimbudarz
> 
> Can you rerun the job with debug logging enabled? ![image](https://user-images.githubusercontent.com/3999494/195782023-be85c061-8a13-44a6-95ee-8f8fd9e21fe2.png)

```
##[debug]Evaluating condition for step: 'Inclusiveness Analyzer'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Inclusiveness Analyzer
##[debug]Loading inputs
##[debug]Loading env
Run microsoft/InclusivenessAnalyzer@v1.0.0
Notice: Inclusiveness Analyzer
Notice: - Scanning files added or modified in last commit
##[debug]git branch: add_inclusivity_check
##[debug]git commit: f343b975d478807ec46461a210c6adcbc2839050
##[debug]git fetch: +f343b975d478807ec46461a210c6adcbc2839050:refs/remotes/origin/add_inclusivity_check
##[debug]
##[debug]git show: 
##[debug]
##[debug]Scanning file: 
Error: ENOENT: no such file or directory, stat
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Inclusiveness Analyzer
```

**Comment by cblomart** [comment]
Looks like "git show" didn't find the modified or added file.
Is the repository you're working on public? if it is can you share a link to it?

Anyhow the ENOENT is not intended and we need to look into it. (looks like "" string)

**Comment by jimbudarz** [comment]
Unfortunately the repo in question is Private. Please let me know if I can gather any other information for you.

**Comment by jimbudarz** [comment]
`git show` shows me that my latest commit actually only renamed a file, resulting in no added or modified files and an empty `git show` output.
If you're using `git show` to list changed files, maybe it would be better not to filter them at all and treat any change as a changed file.

**Comment by cblomart** [comment]
@jimbudarz as we need to properly handle cases where `git show` returns an empty string I've released `v1.0.1`.

Can you crosscheck this solves the issue on your end?

Do you still feel that we should treat rename as a changed file and (re)check the content?

**Comment by jimbudarz** [comment]
I don't mind either way with respect to renamed files.

**Comment by cblomart** [comment]
Thanks @jimbudarz!
waiting for your feedback to see if the new versions solves your issue before closing.

**Comment by james-gibson** [comment]
Similar issue experienced here, private repo, here's relevant config/logs while running `v1.0.1`. Never used on our repo before today and when I switched `v1.0.1` to `v0.1.6-beta` the action began working

Yaml:
```
name: Validate

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Inclusiveness-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Inclusiveness Analyzer
        uses: microsoft/InclusivenessAnalyzer@v1.0.1
```

Debug Logs
```
##[debug]Evaluating condition for step: 'Inclusiveness Analyzer'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Inclusiveness Analyzer
##[debug]Loading inputs
##[debug]Loading env
Run microsoft/InclusivenessAnalyzer@v1.0.1
  with:
    failOnNonInclusiveTerm: false
    excludeUnchangedFiles: true
  env:
    GITHUB_TOKEN: ***
Notice: Inclusiveness Analyzer
Notice: - Scanning files added or modified in last commit
##[debug]git branch: 
##[debug]git commit: 6a1d6cfdb7236dca2b72b8d2443ca0d11e15
fatal: invalid refspec '+2a13d6cfdb236d4ca2b72bd52443ca0de15:refs/remotes/origin/'
Error: Command failed: git fetch -q --no-tags --no-recurse-submodules --depth=2 origin +62ad6cfdb7236d4ca2b72b8d52443ca0d11e:refs/remotes/origin/
fatal: invalid refspec '+62a13d6cfdb76d4ca2b72b8d543ca0d11e15:refs/remotes/origin/'

##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Inclusiveness Analyzer
```

**Comment by jimbudarz** [comment]
> Thanks @jimbudarz! waiting for your feedback to see if the new versions solves your issue before closing.

LGTM!
